---
title: "326.212 Final Project: Part 3 - Q1"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE, 
                      message = FALSE, warning = FALSE)
```

```{r packages, include = FALSE}
# 추가로 필요한 패키지가 있다면 이곳에 작성하시오.
library(tidyverse)
library(tmap)
library(sf)
library('lubridate')
library(forcats)

```

## 2019 - 15993 Lee seung heon

```{r, include = FALSE}
Measurement_info <-read.csv("data/Measurement_info.csv")
Measurement_item_info <-read.csv("data/Measurement_item_info.csv")
Measurement_station_info <-read.csv("data/Measurement_station_info.csv")
```


```{r, include = FALSE}

Measurement_relational_info <- Measurement_info %>% 
  inner_join(Measurement_item_info, by = "Item.code") %>% inner_join(Measurement_station_info, by = "Station.code")

```


```{r, include = FALSE}
level <- c("Good(Blue)", "Normal(Green)", "Bad(Yellow)", "Very bad(Red)")
Pollution_level <- vector("character", nrow(Measurement_relational_info))
value<-unlist(Measurement_relational_info[,4])
t1 <- unlist(Measurement_relational_info[,8])
t2 <- unlist(Measurement_relational_info[,9])
t3 <- unlist(Measurement_relational_info[,10])
t4 <- unlist(Measurement_relational_info[,11])
  
for ( i in seq_len(nrow(Measurement_relational_info))) {
  
   if (value[[i]]<0) {Pollution_level[i] <- NA}
  
   else if (value[[i]]<=t1[[i]]) {Pollution_level[i] <- level[1]}
     
   else if (value[[i]]<=t2[[i]]) {Pollution_level[i] <- level[2]}
  
   else if (value[[i]]<=t3[[i]]) {Pollution_level[i] <- level[3]}
  
   else if (value[[i]]<=t4[[i]]) {Pollution_level[i] <- level[4]}
   
   else if (value[[i]]>t4[[i]]) {Pollution_level[i] <- NA}
  
}
pollution_level <- tibble(Pollution_level)


Measurement_relational_info <- Measurement_relational_info %>% cbind(pollution_level)

```

```{r, include = FALSE}
Measurement_relational_info <- Measurement_relational_info %>% select(
-Station.code , -Address, -Latitude, -Longitude, -Item.code, -Unit.of.measurement, -Good.Blue., -Normal.Green., -Bad.Yellow., -Very.bad.Red.)

```


```{r, include = FALSE}
Measurement_relational_info$Measurement.date <- as.factor(Measurement_relational_info$Measurement.date)
Measurement_relational_info$Item.name <- as.factor(Measurement_relational_info$Item.name)
Measurement_relational_info$Station.name.district. <- as.factor(Measurement_relational_info$Station.name.district.)
Measurement_relational_info$Pollution_level <- as.factor(Measurement_relational_info$Pollution_level)
```

```{r, include = FALSE}
Measurement_relational_info <- Measurement_relational_info %>% filter(!is.na(Pollution_level))
```


```{r, include = FALSE}

Measurement_relational_info <- Measurement_relational_info %>% filter(Instrument.status == 0)
```

```{r, include = FALSE}
Year <- Measurement_relational_info$Measurement.date %>% year()
Month <-Measurement_relational_info$Measurement.date %>% month()
Day <- Measurement_relational_info$Measurement.date %>% day()
Hour <- Measurement_relational_info$Measurement.date %>% hour()
```

```{r, include = FALSE}
Year <- tibble(Year)
Month <- tibble(Month)
Day <- tibble(Day)
Hour <- tibble(Hour)
Measurement_relational_info <- cbind(Year, Month, Day, Hour, Measurement_relational_info)

```

## Part 3 - Q1

### [문제 1]

```{r}
korea_shp <- st_read("data/SIG.shp")
korea_shp$SIG_KOR_NM <- iconv(korea_shp$SIG_KOR_NM, from = "CP949", to = "UTF-8")
seoul_shp <- korea_shp %>% filter(str_detect(SIG_CD,"^11"))
map_seoul <- tm_shape(seoul_shp) + tm_fill() + tm_borders()
print(map_seoul)
```
```{r}
Average_PM2.5 <- Measurement_relational_info %>% filter(Item.name == "PM2.5") %>% group_by(Year, Station.name.district.) %>% summarise(mean(Average.value)) %>% rename(SIG_ENG_NM = Station.name.district.)
```

```{r}
Average_PM2.5_2017 <- Average_PM2.5 %>% filter(Year == 2017) %>% rename(value_PM2.5_2017= `mean(Average.value)`)
Average_PM2.5_2018 <- Average_PM2.5 %>% filter(Year == 2018) %>% rename(value_PM2.5_2018= `mean(Average.value)`)
Average_PM2.5_2019 <-  Average_PM2.5 %>% filter(Year == 2019) %>% rename(value_PM2.5_2019= `mean(Average.value)`)
```

```{r}
seoul_shp_2017<-inner_join(seoul_shp, Average_PM2.5_2017)
seoul_shp_2018<-inner_join(seoul_shp, Average_PM2.5_2018)
seoul_shp_2019<-inner_join(seoul_shp, Average_PM2.5_2019)

map_seoul_2017 <- tm_shape(seoul_shp_2017) + tm_fill(col = "value_PM2.5_2017") + tm_borders()
map_seoul_2018 <- tm_shape(seoul_shp_2018) + tm_fill(col = "value_PM2.5_2018") + tm_borders()
map_seoul_2019 <- tm_shape(seoul_shp_2019) + tm_fill(col = "value_PM2.5_2019") + tm_borders()

print(map_seoul_2017)
print(map_seoul_2018)
print(map_seoul_2019)

```

위 그림을 보면 세 해 모두 대체적으로 남서쪽 방향이 미세먼지 PM2.5의 농도가 다른 방위에 비해서 심한 것을 확인할 수 있다. 


### [문제 2]

기존 데이터에 season 변수를 추가하자.

```{r}

season_levels <- c("winter", "spring", "summer", "fall")
season <- vector("character", nrow(Measurement_relational_info))
month<-unlist(Measurement_relational_info[,2])

for ( i in seq_len(nrow(Measurement_relational_info))) {
  if (month[[i]] == 12 | month[[i]]<=2) {season[i] <- season_levels[1]}
  else if (month[[i]] <= 5) {season[i] <- season_levels[2]}
  else if (month[[i]] <= 8) {season[i] <- season_levels[3]}
  else if (month[[i]] <= 11) {season[i] <- season_levels[4]}
}
season <- tibble(season)
season_info <- cbind(season,Measurement_relational_info)
```

```{r}
Average_NO2 <- season_info %>% filter(Item.name == "NO2") %>% group_by(season, Station.name.district.) %>% summarise(mean(Average.value)) %>% rename(SIG_ENG_NM = Station.name.district.) 

```

```{r}
Average_NO2_winter <- Average_NO2 %>% filter(season ==  "winter") %>% rename(Value_NO2_winter = `mean(Average.value)` )
Average_NO2_spring <- Average_NO2 %>% filter(season ==  "spring") %>% rename(Value_NO2_spring = `mean(Average.value)` )
Average_NO2_summer <- Average_NO2 %>% filter(season ==  "summer") %>% rename(Value_NO2_summer = `mean(Average.value)` )
Average_NO2_fall <- Average_NO2 %>% filter(season ==  "fall") %>% rename(Value_NO2_fall = `mean(Average.value)` )
```

```{r}
seoul_shp_winter <- inner_join(seoul_shp,Average_NO2_winter) 
seoul_shp_spring <- inner_join(seoul_shp,Average_NO2_spring)
seoul_shp_summer <- inner_join(seoul_shp,Average_NO2_summer)
seoul_shp_fall <- inner_join(seoul_shp,Average_NO2_fall) 
```

```{r}
breaks = seq(0.01, 0.045, by = 0.005)

map_seoul_winter <- tm_shape(seoul_shp_winter) + tm_fill(col = "Value_NO2_winter", breaks = breaks) + tm_borders()
print(map_seoul_winter)

map_seoul_spring <- tm_shape(seoul_shp_spring) + tm_fill(col = "Value_NO2_spring", breaks = breaks) + tm_borders()
print(map_seoul_spring)

map_seoul_summer <- tm_shape(seoul_shp_summer) + tm_fill(col = "Value_NO2_summer", breaks = breaks) + tm_borders()
print(map_seoul_summer)

map_seoul_fall <- tm_shape(seoul_shp_fall) + tm_fill(col = "Value_NO2_fall", breaks = breaks) + tm_borders()
print(map_seoul_fall)
```

지역 별 농도를 볼 떄 모든 계절에서 전체적으로 북쪽 상단 지역을 제외하고는 모든 방위에서 바교적 높은 농도가 측정됨을 확인할 수 있다. 그리고 계절별로는 겨울>봄>가을>여름 순으로 농도가 높은 것을 확인할 수 있다. 겨울에서 여름으로 가면서 농도가 점차 감소하고, 여름에서 겨울이 되면서 다시 농도가 증가하는 경향을 보인다.

